- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  setPreference: false # Frontier
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 10800
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  # special: # Frontier
  # - !type:GiveItemOnHolidaySpecial # Frontier
  #   holiday: DoctorDay # Frontier
  #   prototype: WehMedipen # Frontier
  special:
<<<<<<< HEAD
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      SpeedModifier: 1.75
=======
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen
  alternateTitles:
  - MedicalDoctorPhysician
  - MedicalDoctorNurse
  - MedicalDoctorSurgeon
>>>>>>> 5149aaa14ff (Cosmetic Job Titles (#2407))

- type: startingGear
  id: DoctorGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    #storage:
    #back:
    #- Stuff

- type: jobAlternateTitle
  id: MedicalDoctorSurgeon
  name: job-name-alt-medical-1

- type: jobAlternateTitle
  id: MedicalDoctorNurse
  name: job-name-alt-medical-2

- type: jobAlternateTitle
  id: MedicalDoctorPhysician
  name: job-name-alt-medical-3
