- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  setPreference: false # Frontier
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 10800
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
<<<<<<< HEAD
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      SpeedModifier: 1.75
=======
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - External # goobstation
  extendedAccess:
  - Chemistry
  alternateTitles:
  - ParamedicTraumaSpecialist
  - ParamedicEmergencyMedicalTechnician
>>>>>>> 5149aaa14ff (Cosmetic Job Titles (#2407))

- type: startingGear
  id: ParamedicGear
  equipment:
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalEMTFilled
  storage:
    back:
    - EmergencyRollerBedSpawnFolded

- type: jobAlternateTitle
  id: ParamedicTraumaSpecialist
  name: job-name-alt-paramedic-1

- type: jobAlternateTitle
  id: ParamedicEmergencyMedicalTechnician
  name: job-name-alt-paramedic-2
