using System.Linq;
using Content.Client.Administration.Managers;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Triad.ContrabandPermit;
using Content.Shared.Access.Components;
using Content.Shared.Access.Systems;
using Content.Shared.Administration;
using Content.Shared.Whitelist;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ColorNaming;
using Robust.Shared.Prototypes;

namespace Content.Client._Triad.ContrabandPermit;

[GenerateTypedNameReferences]
public sealed partial class ContrabandPermitConsoleWindow : FancyWindow
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private ILocalizationManager _localization = default!;
    [Dependency] private IClientAdminManager _admin = default!;

    private readonly IPlayerManager _player;

    private readonly AccessReaderSystem _accessReader;
    private readonly EntityWhitelistSystem _whitelist;

    private EntityUid? _owner;
    private ContrabandPermitConsoleTab _currentTab = ContrabandPermitConsoleTab.PermitList;
    private ContrabandPermitConsoleEntry[]? _entries = null;
    private ContrabandPermitConsoleOwner? _trackedFocusOwner;

    public event Action<string>? OnReasonChanged;
    public event Action? OnGrantButtonPressed;
    public event Action<string>? OnRevokeButtonPressed;
    public event Action? OnPrintButtonPressed;
    public event Action<ContrabandPermitConsoleOwner?, ContrabandPermitConsoleItem?>? SendFocusChangeMessage;

    public ContrabandPermitConsoleWindow(IPlayerManager playerManager)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _player = playerManager;
        _accessReader = _entManager.System<AccessReaderSystem>();
        _whitelist = _entManager.System<EntityWhitelistSystem>();

        // Mode switching
        PermitListTabButton.OnPressed += PermitListTabPressed;
        GrantPermitTabButton.OnPressed += GrantPermitTabPressed;

        // Permit reason text box
        PermitReasonTextBox.OnTextEntered += e => OnReasonChanged?.Invoke(e.Text);
        PermitReasonTextBox.OnFocusExit += e => OnReasonChanged?.Invoke(e.Text);

        // Grant button
        GrantButton.OnPressed += _ => OnGrantButtonPressed?.Invoke();

        // Print chip button
        ContrabandPermitPrintButton.OnPressed += _ => OnPrintButtonPressed?.Invoke();

        var tabGroup = new ButtonGroup();
        PermitListTabButton.Group = tabGroup;
        GrantPermitTabButton.Group = tabGroup;

        PermitListTabButton.Pressed = true;
        SetupTab(_currentTab);
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;

        if (_entManager.TryGetComponent<ContrabandPermitConsoleComponent>(_owner, out var console))
            _trackedFocusOwner = console.FocusedEntry?.PermitOwner;
    }

    private void PermitListTabPressed(BaseButton.ButtonEventArgs obj)
    {
        ChangeTab(ContrabandPermitConsoleTab.PermitList);
    }

    private void GrantPermitTabPressed(BaseButton.ButtonEventArgs obj)
    {
        ChangeTab(ContrabandPermitConsoleTab.PermitGranter);
    }

    private void SetupTab(ContrabandPermitConsoleTab tab)
    {
        // Clear the modes, then set it up
        PermitListContainer.Visible = false;
        PermitGranterContainer.Visible = false;

        switch (tab)
        {
            case ContrabandPermitConsoleTab.PermitList:
                PermitListContainer.Visible = true;
                break;
            case ContrabandPermitConsoleTab.PermitGranter:
                PermitGranterContainer.Visible = true;
                break;
            default:
                throw new NotImplementedException();
        }
    }

    public void ChangeTab(ContrabandPermitConsoleTab tab)
    {
        if (_currentTab == tab)
            return;

        _currentTab = tab;
        SetupTab(_currentTab);
    }

    public enum ContrabandPermitConsoleTab : byte
    {
        PermitList,
        PermitGranter,
    }

    public void UpdateEntries(ContrabandPermitConsoleEntry[] entries, PermitEntryFocusData? focusData)
    {
        if (_owner == null)
            return;

        if (!_entManager.TryGetComponent<ContrabandPermitConsoleComponent>(_owner.Value, out var consoleComp))
            return;

        if (_trackedFocusOwner?.Owner != focusData?.PermitOwner.Owner)
            focusData = null;

        _entries = entries;

        // Clear excess children from the tables
        var entryCount = _entries.Length;

        while (ActivePermitsTable.ChildCount > entryCount)
            ActivePermitsTable.RemoveChild(ActivePermitsTable.GetChild(ActivePermitsTable.ChildCount - 1));

        // Update all entries in each table
        for (var index = 0; index < _entries.Length; index++)
        {
            var entry = _entries.ElementAt(index);
            UpdateUIEntry(entry, index, ActivePermitsTable, consoleComp, focusData);
        }

        if (entryCount == 0)
        {
            var label = new RichTextLabel()
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            };

            label.SetMarkup(Loc.GetString("contraband-permit-no-permits"));

            ActivePermitsTable.AddChild(label);
        }

        if (consoleComp.CurrentPermitReason != string.Empty && !PermitReasonTextBox.HasKeyboardFocus())
            PermitReasonTextBox.Text = consoleComp.CurrentPermitReason;
    }

    private void UpdateUIEntry(ContrabandPermitConsoleEntry entry, int index, Control table, ContrabandPermitConsoleComponent console, PermitEntryFocusData? focusData)
    {
        if (_owner == null)
            return;

        if (!_entManager.TryGetComponent<ContrabandPermitConsoleComponent>(_owner.Value, out var consoleComp))
            return;

        var items = entry.Items;

        var owner = entry.Owner;

        // Make new UI entry if required
        if (index >= table.ChildCount)
        {
            var newEntryContainer = new ContrabandPermitEntryContainer(owner, items, this, _owner);

            // On click
            newEntryContainer.FocusButton.OnButtonUp += args =>
            {
                var currentOwner = newEntryContainer.PermitOwner.Owner;
                if (_trackedFocusOwner?.Owner == currentOwner)
                {
                    _trackedFocusOwner = null;
                    UpdateFocus(null, null);
                }
                else
                {
                    _trackedFocusOwner = newEntryContainer.PermitOwner;
                    UpdateFocus(newEntryContainer.PermitOwner, null);
                }
            };

            var hasAccess = _player.LocalEntity is not { } localPlayer ||
                            !_entManager.TryGetComponent<AccessReaderComponent>(_owner, out var access) ||
                            _accessReader.IsAllowed(localPlayer, _owner.Value, access);

            newEntryContainer.RevokeButton.Disabled = !hasAccess;
            newEntryContainer.RevokeReasonTextBox.Editable = hasAccess;

            newEntryContainer.RevokeButton.OnPressed += args =>
            {
                var reason = newEntryContainer.RevokeReasonTextBox.Text;
                SendRevokeButtonMessage(reason);
            };

            // Add the entry to the current table
            table.AddChild(newEntryContainer);
        }

        // Update values and UI elements
        var tableChild = table.GetChild(index);

        if (tableChild is not ContrabandPermitEntryContainer)
        {
            table.RemoveChild(tableChild);
            UpdateUIEntry(entry, index, table, console, focusData);
            return;
        }

        var entryContainer = (ContrabandPermitEntryContainer)tableChild;
        entryContainer.UpdatePermitOwnerAndEntries(owner, items);
        entryContainer.UpdateEntry(focusData);
    }

    public void UpdateFocus(ContrabandPermitConsoleOwner? owner, ContrabandPermitConsoleItem? item)
    {
        SendFocusChangeMessage?.Invoke(owner, item);
    }

    public void SendRevokeButtonMessage(string reason)
    {
        OnRevokeButtonPressed?.Invoke(reason);
    }

    public void UpdateState(ContrabandPermitConsoleBuiState state)
    {
        if (_owner == null)
            return;

        if (!_entManager.TryGetComponent<ContrabandPermitConsoleComponent>(_owner.Value, out var consoleComp))
            return;

        var validWhitelist = true;
        if (consoleComp.GrantPermitWhitelist != null
            && _player.LocalEntity != null
            && !_admin.HasFlag(AdminFlags.Admin))
        {
            if (_whitelist.CheckBoth(_player.LocalEntity, consoleComp.GrantPermitBlacklist, consoleComp.GrantPermitWhitelist))
                validWhitelist = true;
            else
                validWhitelist = false;
        }

        UpdateEntries(state.Entries, state.FocusData);

        if (state.InsertedChip != null && validWhitelist)
        {
            UpdateInsertedChipInfo(state, state.InsertedChip.Value);
        }
        else
        {
            // Show the no access/no item screen
            NoItemInsertedScreen.Visible = true;
            PermitGranterLeft.Visible = false;
            PermitGranterRight.Visible = false;

            if (!validWhitelist)
                NoItemInsertedLabel.Text = Loc.GetString("contraband-permit-console-window-permit-grant-no-access");
            else
                NoItemInsertedLabel.Text = Loc.GetString("contraband-permit-console-window-permit-grant-no-item");
        }
    }

    private void UpdateInsertedChipInfo(ContrabandPermitConsoleBuiState state, NetEntity chipNetEnt)
    {
        NoItemInsertedScreen.Visible = false;
        PermitGranterLeft.Visible = true;
        PermitGranterRight.Visible = true;

        var insertedChip = _entManager.GetEntity(chipNetEnt);

        if (!_entManager.TryGetComponent<ContrabandPermitChipComponent>(insertedChip, out var chip))
            return;

        var carrier = chip.ScannedPermitCarrier;
        var scannedItem = chip.ScannedItem;

        if (carrier == null || scannedItem == null)
        {
            // Reset info
            PermitItemView.SetEntity(null);
            OwnerNameLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-name", ("name", string.Empty));
            OwnerSpeciesLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-species", ("species", string.Empty));
            OwnerAgeLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-age", ("age", string.Empty));
            OwnerGenderLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-gender", ("gender", string.Empty));
            OwnerEyeColorLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-eye-color", ("color", string.Empty));

            ItemNameLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-item-name", ("name", string.Empty));
            DateGrantedLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-date", ("date", string.Empty));
            return;
        }

        if (state.OwnerInfo is { } info)
        {
            OwnerNameLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-name", ("name", info.ScannedOwnerName));
            OwnerSpeciesLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-species", ("species", info.ScannedOwnerSpecies));
            OwnerAgeLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-age", ("age", info.ScannedOwnerAge));
            OwnerGenderLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-gender", ("gender", info.ScannedOwnerGender.ToString()));
            OwnerEyeColorLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-eye-color", ("color", info.ScannedOwnerEyeColor));
        }

        if (_prototype.TryIndex(state.ScannedItemProtoId, out var prototype))
        {
            PermitItemView.SetPrototype(prototype);

            ItemNameLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-item-name", ("name", prototype.Name));
            DateGrantedLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-date", ("date", state.DateTime ?? string.Empty));
        }
    }
}
