using System.Linq;
using Content.Shared._Triad.ContrabandPermit;
using Content.Shared._Triad.Humanoid;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ColorNaming;
using Robust.Shared.Prototypes;

namespace Content.Client._Triad.ContrabandPermit;

[GenerateTypedNameReferences]
public sealed partial class ContrabandPermitEntryContainer : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private ILocalizationManager _localization = default!;

    public EntityUid? ConsoleEntity;
    public NetEntity PermitOwner;
    public List<NetEntity> PermitItems;

    private readonly ContrabandPermitConsoleWindow? _window;
    private readonly ButtonGroup _permitItemButtons = new();

    public ContrabandPermitEntryContainer(NetEntity uid, List<NetEntity> items, ContrabandPermitConsoleWindow window, EntityUid? consoleEntity)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PermitOwner = uid;
        PermitItems = items;
        _window = window;
        ConsoleEntity = consoleEntity;
    }

    public void UpdatePermitOwnerAndEntries(NetEntity uid, List<NetEntity> items)
    {
        PermitOwner = uid;
        PermitItems = items;
    }

    public void UpdateEntry(PermitEntryFocusData? focusData = null)
    {
        if (ConsoleEntity == null)
            return;

        var ownerName = string.Empty;
        var ownerEntity = _entManager.GetEntity(PermitOwner);

        if (_entManager.TryGetComponent<MetaDataComponent>(ownerEntity, out var meta))
            ownerName = meta.EntityName;

        // Set the sprite view to the owner if it is a humanoid view
        if (_entManager.HasComponent<HumanoidViewerEntityComponent>(ownerEntity))
            PermitOwnerSprite.SetEntity(ownerEntity);

        // Update owner name and amount of permits
        PermitOwnerNameLabel.Text = ownerName;
        PermitAmountLabel.Text = Loc.GetString("contraband-permit-console-window-permit-owner-entries", ("number", PermitItems.Count));

        FocusContainer.Visible = false;

        // Clear children if not the focus
        if (!_entManager.EntityExists(ownerEntity) || focusData == null || focusData.Value.PermitOwner != PermitOwner)
        {
            PermitScrollContainer.RemoveAllChildren();
            return;
        }

        FocusContainer.Visible = true;

        var hasItemSelected = focusData.Value.SelectedItem != null;
        NoItemSelectedScreen.Visible = !hasItemSelected;
        PermitViewContainer.Visible = hasItemSelected;

        // Clear excess children from the tables when updating
        var itemCount = PermitItems.Count;

        while (PermitScrollContainer.ChildCount > itemCount)
            PermitScrollContainer.RemoveChild(PermitScrollContainer.GetChild(PermitScrollContainer.ChildCount - 1));

        // Update all entries in each table
        for (var index = 0; index < PermitItems.Count; index++)
        {
            var entry = PermitItems.ElementAt(index);
            UpdateContainer(entry, ownerEntity, PermitScrollContainer, index, focusData.Value);
        }
    }

    private void UpdateContainer(NetEntity item, EntityUid permitOwner, Control table, int index, PermitEntryFocusData focusData)
    {
        var isSelectedItem = focusData.SelectedItem == item;
        var itemEntity = _entManager.GetEntity(item);

        if (!_entManager.TryGetComponent<MetaDataComponent>(itemEntity, out var itemMeta))
            return;

        if (itemMeta.EntityPrototype == null)
            return;

        if (!_entManager.EntityExists(itemEntity))
            return;

        if (isSelectedItem && _entManager.TryGetComponent<ContrabandPermitItemComponent>(itemEntity, out var permit))
        {
            // Set item info
            if (itemMeta.EntityPrototype != null)
            {
                ItemPrototype.SetPrototype(itemMeta.EntityPrototype);
                ItemLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-item-name", ("name", itemMeta.EntityPrototype.Name));
            }

            DateLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-date", ("date", permit.DateGranted));
            ReasonLabel.Text = Loc.GetString("contraband-permit-console-window-label-permit-tab-reason", ("reason", permit.PermitReason));

            // Now owner info
            OwnerNameLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-name", ("name", permit.PermitOwnerName));

            if (_entManager.TryGetComponent<HumanoidAppearanceComponent>(permitOwner, out var humanoidAppearance))
            {
                var species = _prototype.Index(humanoidAppearance.Species);
                var speciesName = Loc.GetString(species.Name);
                OwnerSpeciesLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-species", ("species", speciesName));

                OwnerAgeLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-age", ("age", humanoidAppearance.Age));

                var gender = humanoidAppearance.Gender.ToString();
                OwnerGenderLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-gender", ("gender", gender));

                var colorName = ColorNaming.Describe(humanoidAppearance.EyeColor, _localization);
                OwnerEyeColorLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-eye-color", ("color", colorName));
            }
        }

        // Make new buttons if needed
        if (index >= table.ChildCount)
        {
            var itemIndex = index;
            var newButton = new Button
            {
                ToggleMode = true,
                HorizontalExpand = true,
                Group = _permitItemButtons
            };

            newButton.OnPressed += args =>
            {
                if (itemIndex < PermitItems.Count)
                    _window?.UpdateFocus(PermitOwner, PermitItems[itemIndex]);
            };

            table.AddChild(newButton);
        }

        // Keep reused buttons in sync with the current item list
        if (table.GetChild(index) is Button button)
        {
            button.Text = itemMeta.EntityName;
            button.Pressed = isSelectedItem;
        }
    }
}
