using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Triad.ContrabandPermit;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using System.Diagnostics.CodeAnalysis;
using System.Linq;

namespace Content.Client._Triad.ContrabandPermit;

[GenerateTypedNameReferences]
public sealed partial class ContrabandPermitConsoleWindow : FancyWindow
{
    private EntityUid? _owner;
    private ContrabandPermitConsoleTab _currentTab = ContrabandPermitConsoleTab.PermitList;

    public ContrabandPermitConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this); // Frontier

        // Mode switching
        PermitListTabButton.OnPressed += PermitListTabPressed;
        GrantPermitTabButton.OnPressed += GrantPermitTabPressed;

        var tabGroup = new ButtonGroup();
        PermitListTabButton.Group = tabGroup;
        GrantPermitTabButton.Group = tabGroup;

        PermitListTabButton.Pressed = true;
        SetupTab(_currentTab);
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
        PermitOwnerView.SetEntity(owner);
    }

    private void PermitListTabPressed(BaseButton.ButtonEventArgs obj)
    {
        ChangeTab(ContrabandPermitConsoleTab.PermitList);
    }

    private void GrantPermitTabPressed(BaseButton.ButtonEventArgs obj)
    {
        ChangeTab(ContrabandPermitConsoleTab.PermitGranter);
    }

    private void SetupTab(ContrabandPermitConsoleTab tab)
    {
        // Clear the modes, then set it up
        PermitListContainer.Visible = false;
        PermitGranterContainer.Visible = false;

        switch (tab)
        {
            case ContrabandPermitConsoleTab.PermitList:
                PermitListContainer.Visible = true;
                break;
            case ContrabandPermitConsoleTab.PermitGranter:
                PermitGranterContainer.Visible = true;
                break;
            default:
                throw new NotImplementedException();
        }
    }

    public void ChangeTab(ContrabandPermitConsoleTab tab)
    {
        if (_currentTab == tab)
            return;

        _currentTab = tab;
        SetupTab(_currentTab);
    }

    public enum ContrabandPermitConsoleTab : byte
    {
        PermitList,
        PermitGranter,
    }

    public void UpdateUI()
    {
        if (_owner == null)
            return;

        var activePermitCount = 0;

        if (activePermitCount == 0)
        {
            var label = new RichTextLabel()
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            };

            label.SetMarkup(Loc.GetString("contraband-permit-no-permits"));

            ActivePermitsTable.AddChild(label);
        }
    }
}
