using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._Triad.ContrabandPermit;

[GenerateTypedNameReferences]
public sealed partial class ContrabandPermitEntry : BoxContainer
{
    public NetEntity PermitOwner;

    private readonly IConfigurationManager _config;
    private readonly IEntityManager _entManager;
    private readonly IResourceCache _cache;

    // Colors
    private readonly Color _colorGray = Color.Gray;
    private readonly Color _colorSlate = Color.LightSlateGray;

    public ContrabandPermitEntry(NetEntity uid)
    {
        RobustXamlLoader.Load(this);

        _config = IoCManager.Resolve<IConfigurationManager>();
        _entManager = IoCManager.Resolve<IEntityManager>();
        _cache = IoCManager.Resolve<IResourceCache>();

        PermitOwner = uid;


    }
}
