using System.Linq;
using Content.Shared._Triad.ContrabandPermit;
using Content.Shared.Humanoid;
using Content.Shared.Inventory;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ColorNaming;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;

namespace Content.Client._Triad.ContrabandPermit;

[GenerateTypedNameReferences]
public sealed partial class ContrabandPermitEntryContainer : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private ILocalizationManager _localization = default!;

    private readonly SharedHumanoidAppearanceSystem _humanoid;
    private readonly MetaDataSystem _metaData;
    private readonly InventorySystem _inventory;

    public EntityUid? ConsoleEntity;

    public EntityUid? PermitOwnerPreview;
    public ContrabandPermitConsoleOwner PermitOwner;
    public List<ContrabandPermitConsoleItem> PermitItems;

    private readonly ContrabandPermitConsoleWindow? _window;
    private readonly ButtonGroup _permitItemButtons = new();

    public ContrabandPermitEntryContainer(ContrabandPermitConsoleOwner uid, List<ContrabandPermitConsoleItem> items, ContrabandPermitConsoleWindow window, EntityUid? consoleEntity)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _humanoid = _entManager.System<SharedHumanoidAppearanceSystem>();
        _metaData = _entManager.System<MetaDataSystem>();
        _inventory = _entManager.System<InventorySystem>();

        PermitOwner = uid;
        PermitItems = items;
        _window = window;
        ConsoleEntity = consoleEntity;
    }

    public void UpdatePermitOwnerAndEntries(ContrabandPermitConsoleOwner uid, List<ContrabandPermitConsoleItem> items)
    {
        PermitOwner = uid;
        PermitItems = items;
    }

    public void UpdateEntry(PermitEntryFocusData? focusData = null)
    {
        if (ConsoleEntity == null)
            return;

        var ownerSpecies = _prototype.Index(PermitOwner.Species);
        UpdatePreviewDummy(PermitOwner, ownerSpecies.DollPrototype);

        // Update amount of permits
        PermitOwnerNameLabel.Text = PermitOwner.Name;
        PermitAmountLabel.Text = Loc.GetString("contraband-permit-console-window-permit-owner-entries", ("number", PermitItems.Count));

        FocusContainer.Visible = false;

        // Clear children if not the focus
        if (focusData == null || focusData.Value.PermitOwner.Owner != PermitOwner.Owner)
        {
            PermitScrollContainer.RemoveAllChildren();
            return;
        }

        FocusContainer.Visible = true;

        var hasItemSelected = focusData.Value.SelectedItem != null;
        NoItemSelectedScreen.Visible = !hasItemSelected;
        PermitViewContainer.Visible = hasItemSelected;

        // Clear excess children from the tables when updating
        var itemCount = PermitItems.Count;

        while (PermitScrollContainer.ChildCount > itemCount)
            PermitScrollContainer.RemoveChild(PermitScrollContainer.GetChild(PermitScrollContainer.ChildCount - 1));

        // Update all entries in each table
        for (var index = 0; index < PermitItems.Count; index++)
        {
            var entry = PermitItems.ElementAt(index);
            UpdateContainer(entry, PermitOwner, PermitScrollContainer, index, focusData.Value);
        }
    }

    private void UpdateContainer(ContrabandPermitConsoleItem itemData, ContrabandPermitConsoleOwner permitOwner, Control table, int index, PermitEntryFocusData focusData)
    {
        var isSelectedItem = focusData.SelectedItem?.Item == itemData.Item;

        if (!_prototype.TryIndex(itemData.Prototype, out var prototype))
            return;

        if (isSelectedItem)
        {
            // Set item info
            ItemPrototype.SetPrototype(itemData.Prototype);
            ItemLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-item-name", ("name", prototype.Name));

            DateLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-date", ("date", itemData.DateGranted));
            ReasonLabel.Text = Loc.GetString("contraband-permit-console-window-label-permit-tab-reason", ("reason", itemData.PermitReason));

            // Now owner info
            OwnerNameLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-name", ("name", permitOwner.Name));

            var species = _prototype.Index(permitOwner.Species);
            var speciesName = Loc.GetString(species.Name);
            OwnerSpeciesLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-species", ("species", speciesName));

            OwnerAgeLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-age", ("age", permitOwner.Age));

            var gender = permitOwner.Gender.ToString();
            OwnerGenderLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-gender", ("gender", gender));

            var colorName = ColorNaming.Describe(permitOwner.Appearance.EyeColor, _localization);
            OwnerEyeColorLabel.Text = Loc.GetString("contraband-permit-console-window-label-grant-tab-owner-eye-color", ("color", colorName));
        }

        // Make new buttons if needed
        if (index >= table.ChildCount)
        {
            var itemIndex = index;
            var newButton = new Button
            {
                ToggleMode = true,
                HorizontalExpand = true,
                Group = _permitItemButtons
            };

            newButton.OnPressed += args =>
            {
                if (itemIndex < PermitItems.Count)
                    _window?.UpdateFocus(PermitOwner, PermitItems[itemIndex]);
            };

            table.AddChild(newButton);
        }

        // Keep reused buttons in sync with the current item list
        if (table.GetChild(index) is Button button)
        {
            button.Text = prototype.Name;
            button.Pressed = isSelectedItem;
        }
    }

    private void UpdatePreviewDummy(ContrabandPermitConsoleOwner permitOwner, EntProtoId dummyProto)
    {
        _entManager.DeleteEntity(PermitOwnerPreview);

        var newDummy = _entManager.SpawnEntity(dummyProto, MapCoordinates.Nullspace);

        var profile = HumanoidCharacterProfile.RandomWithSpecies(permitOwner.Species);
        profile = profile.WithGender(permitOwner.Gender);
        profile = profile.WithSex(permitOwner.Sex);
        profile = profile.WithAge(permitOwner.Age);
        profile = profile.WithCharacterAppearance(permitOwner.Appearance);

        _humanoid.LoadProfile(newDummy, profile);
        _metaData.SetEntityName(newDummy, permitOwner.Name);

        // Spawn and equip equipment
        foreach (var itemId in permitOwner.ItemsToEquip)
        {
            var newItem = _entManager.SpawnNextToOrDrop(itemId, newDummy);

            var equipped = false;

            // Attempt to equip the clothing item
            var enumerator = _inventory.GetSlotEnumerator(newDummy, SlotFlags.WITHOUT_POCKET);
            while (enumerator.MoveNext(out var slot))
            {
                if (_inventory.TryEquip(newDummy, newItem, slot.ID, force: true, silent: true, checkDoafter: false))
                {
                    equipped = true;
                    break;
                }
            }

            if (!equipped)
                _entManager.DeleteEntity(newItem);
        }

        // Set the sprite view to the spawned preview dummmy
        PermitOwnerSprite.SetEntity(newDummy);
        PermitOwnerPreview = newDummy;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _entManager.DeleteEntity(PermitOwnerPreview);
        PermitOwnerPreview = null;
    }
}
