using System.Numerics;
using Content.Shared._Triad.ContrabandPermit;
using Content.Shared._Triad.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Triad.ContrabandPermit;

[GenerateTypedNameReferences]
public sealed partial class ContrabandPermitEntryContainer : BoxContainer
{
    public NetEntity PermitOwner;
    public List<NetEntity> PermitItems;

    private readonly IEntityManager _entManager;

    public ContrabandPermitEntryContainer(NetEntity uid, List<NetEntity> items)
    {
        RobustXamlLoader.Load(this);

        _entManager = IoCManager.Resolve<IEntityManager>();

        PermitOwner = uid;
        PermitItems = items;
    }

    public void UpdatePermitOwnerAndEntries(NetEntity uid, List<NetEntity> items)
    {
        PermitOwner = uid;
        PermitItems = items;
    }

    public void UpdateEntry(PermitEntryFocusData? focusData = null)
    {
        var ownerName = string.Empty;
        var ownerEntity = _entManager.GetEntity(PermitOwner);

        if (_entManager.TryGetComponent<MetaDataComponent>(ownerEntity, out var meta))
            ownerName = meta.EntityName;

        // Set the sprite view to the owner if it is a humanoid view
        if (_entManager.HasComponent<HumanoidViewerEntityComponent>(ownerEntity))
            PermitOwnerSprite.SetEntity(ownerEntity);

        // Update owner name and amount of permits
        PermitOwnerNameLabel.Text = ownerName;
        PermitAmountLabel.Text = Loc.GetString("contraband-permit-console-window-permit-owner-entries", ("number", PermitItems.Count));

        FocusContainer.Visible = false;

        if (focusData != null && focusData.Value.PermitOwner == PermitOwner)
        {
            FocusContainer.Visible = true;
            PermitScrollContainer.RemoveAllChildren();

            foreach (var item in PermitItems)
            {
                var itemEntity = _entManager.GetEntity(item);

                if (!_entManager.TryGetComponent<MetaDataComponent>(itemEntity, out var itemMeta))
                    continue;

                var selectedItem = focusData.Value.SelectedItem == item;

                var newButton = new Button
                {
                    Text = itemMeta.EntityName,
                    ToggleMode = true,
                    HorizontalExpand = true,
                    Pressed = selectedItem,
                };

                PermitScrollContainer.AddChild(newButton);
            }
        }
    }
}
