// SPDX-FileCopyrightText: 2025 Steve <marlumpy@gmail.com>
// SPDX-FileCopyrightText: 2025 marc-pelletier <113944176+marc-pelletier@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 Triad Sector
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.RCD;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.RCD;

// Triad: RPD port from funky-station (PR #1244) — wraps RCDMenu with a color-picker strip.
[GenerateTypedNameReferences]
public sealed partial class RPDMenu : RadialMenu
{
    [Dependency] private readonly ILocalizationManager _locManager = default!;

    private readonly RCDMenu _rcdMenu;
    private string? _selectedColor;

    public event Action<string>? ColorSelected;

    public event Action<ProtoId<RCDPrototype>>? SendRCDSystemMessageAction
    {
        add => _rcdMenu.SendRCDSystemMessageAction += value;
        remove => _rcdMenu.SendRCDSystemMessageAction -= value;
    }

    public RPDMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _rcdMenu = new RCDMenu();
        var rcdHolder = FindControl<Control>("RCDMenuHolder");
        rcdHolder.AddChild(_rcdMenu);
        _rcdMenu.OnClose += Close;
    }

    public void SetEntity(EntityUid uid)
    {
        _rcdMenu.SetEntity(uid);
    }

    public void Populate(Dictionary<string, Color?> palette, string selectedColor = "default")
    {
        _selectedColor = palette.ContainsKey(selectedColor) ? selectedColor : "default";
        var colorList = FindControl<BoxContainer>("ColorList");
        if (colorList == null)
            return;

        foreach (var child in colorList.Children)
            child.Dispose();
        colorList.RemoveAllChildren();

        foreach (var color in palette)
        {
            var button = new Button
            {
                Name = $"ColorBox_{color.Key}",
                Visible = true,
                MinSize = new Vector2(30, 30),
                MaxSize = new Vector2(30, 30),
                Margin = new Thickness(6),
                StyleClasses = { "OpenBoth" },
                ToolTip = _locManager.GetString(color.Key)
            };

            var colorPanel = new PanelContainer
            {
                MinSize = new Vector2(30, 30),
                MaxSize = new Vector2(30, 30),
                PanelOverride = color.Value != null
                    ? new StyleBoxFlat { BackgroundColor = color.Value.Value }
                    : new StyleBoxFlat { BackgroundColor = Color.Transparent }
            };

            UpdateButtonBorder(colorPanel, color.Key);

            button.OnMouseEntered += _ =>
            {
                if (colorPanel.PanelOverride is not StyleBoxFlat hover)
                    return;
                hover.BorderColor = Color.LightBlue;
                hover.BorderThickness = new Thickness(3);
            };

            button.OnMouseExited += _ => UpdateButtonBorder(colorPanel, color.Key);

            button.OnPressed += _ =>
            {
                if (_selectedColor == color.Key)
                    return;
                _selectedColor = color.Key;
                UpdateAllButtonBorders();
                ColorSelected?.Invoke(_selectedColor);
            };

            button.AddChild(colorPanel);
            colorList.AddChild(button);
        }

        UpdateAllButtonBorders();
    }

    private void UpdateButtonBorder(PanelContainer panel, string colorKey)
    {
        if (panel.PanelOverride is not StyleBoxFlat styleBox)
            return;

        if (_selectedColor == colorKey)
        {
            styleBox.BorderColor = Color.Gold;
            styleBox.BorderThickness = new Thickness(3);
        }
        else
        {
            styleBox.BorderColor = Color.Transparent;
            styleBox.BorderThickness = new Thickness(3);
        }
    }

    private void UpdateAllButtonBorders()
    {
        var colorList = FindControl<BoxContainer>("ColorList");
        if (colorList == null)
            return;

        foreach (var child in colorList.Children)
        {
            if (child is not Button button || button.Name == null)
                continue;

            var colorKey = button.Name.StartsWith("ColorBox_")
                ? button.Name["ColorBox_".Length..]
                : null;
            if (colorKey == null)
                continue;

            var panel = button.Children.OfType<PanelContainer>().FirstOrDefault();
            if (panel != null)
                UpdateButtonBorder(panel, colorKey);
        }
    }
}
