- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetectiveOld
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hours
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
<<<<<<< HEAD
  ## Frontier: commented stuff out below
  # access:
  # - Security
  # - Brig
  # - Maintenance
  # - Service
  # - Detective
  # - Cryogenics
  # - External
  # special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]
  ## Frontier: commented stuff out above
  setPreference: false # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
=======
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Detective
  - Cryogenics
  - External
  # begin Funkystation: give out missing genpop accesses
  - GenpopEnter
  - GenpopLeave
  # end Funkystation
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  alternateTitles:
  - DetectiveForensicInvestigator
>>>>>>> 5149aaa14ff (Cosmetic Job Titles (#2407))

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
<<<<<<< HEAD
=======
    - SecHypo # Goobstation
    - CartridgeEmergency

- type: jobAlternateTitle
  id: DetectiveForensicInvestigator
  name: job-name-alt-detective-1
>>>>>>> 5149aaa14ff (Cosmetic Job Titles (#2407))
