- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficerOld
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 #10 hrs
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
<<<<<<< HEAD
  ## Frontier: commented out stuff below
  # access:
  # - Security
  # - Brig
  # - Maintenance
  # - Service
  # - External
  # - Cryogenics
  # special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]
  ## End Frontier: commented out stuff above
  setPreference: false # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
=======
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  # begin Funkystation: give out missing genpop accesses
  - GenpopEnter
  - GenpopLeave
  # end Funkystation
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  alternateTitles:
  - SecurityOfficerHallMonitor
>>>>>>> 5149aaa14ff (Cosmetic Job Titles (#2407))

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
<<<<<<< HEAD
    - Magazine45_ACPPistolFMJ
=======
    - MagazinePistol
    - SecHypo # Goobstation
    - CartridgeEmergency

- type: jobAlternateTitle
  id: SecurityOfficerHallMonitor
  name: job-name-alt-secoff-1
>>>>>>> 5149aaa14ff (Cosmetic Job Titles (#2407))
