- type: loadout
  id: SeniorDoIJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitSeniorEngineer

- type: loadout
  id: SeniorDoIJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtSeniorEngineer

- type: loadout
  id: PlantManagerMessengerBag
  equipment:
    back: ClothingBackpackMessengerChiefEngineer

- type: loadout
  id: DoICloak
  equipment:
    neck: ClothingNeckCloakCe

- type: loadout
  id: DoIMantle
  equipment:
    neck: ClothingNeckMantleCE

- type: loadout
  id: ClothingOuterWinterCE
  equipment:
    neck: ClothingOuterWinterCE
