- type: job
  id: Boxer
  name: job-name-boxer
  description: job-description-boxer
  playTimeTracker: JobBoxer
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: BoxerGear
  icon: "JobIconBoxer"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: ClothingHandsGlovesBoxingRigged
  alternateTitles:
  - BoxerFitnessInstructor
  - BoxerYogaInstructor
  - BoxerLifeCoach
  - BoxerPersonalTrainer
  - BoxerHeel

- type: startingGear
  id: BoxerGear
  equipment:
    id: BoxerPDA
    ears: ClothingHeadsetService
    shoes: ClothingShoesColorRed
    belt: ClothingBeltChampion
  #storage:
    #back:
    #- Stuff

- type: jobAlternateTitle
  id: BoxerFitnessInstructor
  name: job-name-alt-boxer-1

- type: jobAlternateTitle
  id: BoxerYogaInstructor
  name: job-name-alt-boxer-2

- type: jobAlternateTitle
  id: BoxerLifeCoach
  name: job-name-alt-boxer-3

- type: jobAlternateTitle
  id: BoxerPersonalTrainer
  name: job-name-alt-boxer-4

- type: jobAlternateTitle
  id: BoxerHeel
  name: job-name-alt-boxer-5
