- type: job
  id: Zookeeper
  name: job-name-zookeeper
  description: job-description-zookeeper
  playTimeTracker: JobZookeeper
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: ZookeeperGear
  icon: "JobIconZookeeper"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MonkeyDay
    prototype: MonkeyCubeBox
  alternateTitles:
  - ZookeeperAnimalControl
  - ZookeeperMenagerist
  - ZookeeperXenobiologist
  - ZookeeperWildlifeSpecialist

- type: startingGear
  id: ZookeeperGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSafari
    head: ClothingHeadSafari
    shoes: ClothingShoesColorWhite
    id: ZookeeperPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: jobAlternateTitle
  id: ZookeeperAnimalControl
  name: job-name-alt-zookeeper-1

- type: jobAlternateTitle
  id: ZookeeperMenagerist
  name: job-name-alt-zookeeper-2

- type: jobAlternateTitle
  id: ZookeeperXenobiologist
  name: job-name-alt-zookeeper-3

- type: jobAlternateTitle
  id: ZookeeperWildlifeSpecialist
  name: job-name-alt-zookeeper-4
