- type: job
  id: SecurityGuard
  name: job-name-security-guard
  description: job-description-security-guard
  playTimeTracker: JobSecurityGuard
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000 # Triad - 5 hrs
  startingGear: SecurityGuardGear
  alwaysUseSpawner: true
  icon: "JobIconSecurityGuard"
  supervisors: job-supervisors-sr
  assignedCompany: Colonial
  weight: 80
  displayWeight: 20 # Second from the bottom
  canBeAntag: false
  # Triad, modify access levels
  accessGroups:
  - GeneralTdfAccess
  - AllAccessColonial
  # Triad End
  ranks: # Triad, ranks
    RankEnforcer:
    - !type:RoleTimeRequirement
      role: JobSecurityGuard
      time: 90000 # 25 hours
    RankJuniorEnforcer: []
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ] # Triad - re-add sec implant
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddComponentSpecial # Triad
    components:
      - type: ShipSavingBlacklist # Triad - can't save ships
      - type: NpcFactionMember
        factions:
        - TDF # Station guards were sent to the TFA by the TDF
      - type: CryoSleepRadioOverride
        overrides:
        - Nfsd # TDF radio
        - Service # Colonial Staff radio

- type: startingGear
  id: SecurityGuardGear
  equipment:
    pocket1: WeaponDisabler
  storage:
    back:
    - EncryptionKeyService
    - EncryptionKeySecurity
    - ShipVoucherFrontierGuard
