- type: job
  id: StationRepresentative
  name: job-name-sr
  description: job-description-sr
  playTimeTracker: JobHeadOfPersonnel
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # triad 10 hours
    - !type:RoleTimeRequirement
      role: JobSecurityGuard
      time: 28800 # triad 8 hours
    - !type:RoleTimeRequirement
      role: JobStc
      time: 18000 # triad 5 hours
  whitelisted: true
  startingGear: SrGear
  alwaysUseSpawner: true
  assignedCompany: Colonial
  icon: "JobIconHeadOfSecurity" # Mono
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  weight: 170
  displayWeight: 60 # Top
  canBeAntag: false
  accessGroups:
  - AllAccessSR
  ranks: # Triad, ranks
    RankOverseer: []
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ] # Triad - re-add sec implant
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: NpcFactionMember
        factions:
        - TDF # Triad - They aren't apart of the TDF, but they are friendly and work with them
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SrGear
  equipment:
    pocket1: WeaponEnergyGunLawbringer
  storage:
    back:
    - Flash
    - RubberStampSr
    - DoorRemoteCommand
    - EncryptionKeyCentCom
    - EncryptionKeyStationMasterSR #Mono start
    - EncryptionKeyDiplomacy
    - ShipVoucherFrontierGuard
    - PhoneInstrumentHigh
