using System.Linq; // Triad
using Content.Client._DV.CartridgeLoader.Cartridges; // Triad
using Content.Shared._DV.CartridgeLoader.Cartridges; // Triad
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class LogProbeUiFragment : BoxContainer
{
    /// <summary>
    /// Action invoked when the print button gets pressed.
    /// </summary>
    public Action? OnPrintPressed;

    public LogProbeUiFragment()
    {
        RobustXamlLoader.Load(this);

        PrintButton.OnPressed += _ => OnPrintPressed?.Invoke();
    }

    // Triad begin: the probe now renders either access logs or a scanned TriTalk card
    public void UpdateState(LogProbeUiState state)
    {
        EntityName.Text = state.EntityName;
        PrintButton.Disabled = string.IsNullOrEmpty(state.EntityName);

        ProbedDeviceContainer.RemoveAllChildren();

        if (state.NanoChatData != null)
        {
            SetupNanoChatView(state.NanoChatData.Value);
            DisplayNanoChatData(state.NanoChatData.Value);
        }
        else
        {
            SetupAccessLogView();
            DisplayAccessLogs(state.PulledLogs);
        }
    }

    private void SetupNanoChatView(NanoChatData data)
    {
        TitleLabel.Text = Loc.GetString("log-probe-header-nanochat");
        ContentLabel.Text = Loc.GetString("log-probe-label-message");

        // Show card info if available
        var cardInfo = new List<string>();
        if (data.CardNumber != null)
            cardInfo.Add(Loc.GetString("log-probe-card-number", ("number", $"#{data.CardNumber:D4}")));

        cardInfo.Add(Loc.GetString("log-probe-recipients", ("count", data.Recipients.Count)));

        CardNumberLabel.Text = string.Join(" | ", cardInfo);
        CardNumberLabel.Visible = true;
    }

    private void SetupAccessLogView()
    {
        TitleLabel.Text = Loc.GetString("log-probe-header-access");
        ContentLabel.Text = Loc.GetString("log-probe-label-accessor");
        CardNumberLabel.Visible = false;
    }

    private void DisplayNanoChatData(NanoChatData data)
    {
        // First add a recipient list entry
        var recipientsList = Loc.GetString("log-probe-recipient-list") + "\n" + string.Join("\n",
            data.Recipients.Values
                .OrderBy(r => r.Name)
                .Select(r => $"    {r.Name}" +
                             (string.IsNullOrEmpty(r.JobTitle) ? "" : $" ({r.JobTitle})") +
                             $" | #{r.Number:D4}"));

        var recipientsEntry = new LogProbeUiEntry(0, "---", recipientsList);
        ProbedDeviceContainer.AddChild(recipientsEntry);

        var count = 1;
        foreach (var (partnerId, messages) in data.Messages)
        {
            // Show only successfully delivered incoming messages
            var incomingMessages = messages
                .Where(msg => msg.SenderId == partnerId && !msg.DeliveryFailed)
                .OrderByDescending(msg => msg.Timestamp);

            foreach (var msg in incomingMessages)
            {
                AddNanoChatEntry(count, msg, $"#{msg.SenderId:D4}", $"#{data.CardNumber:D4}");
                count++;
            }

            // Show only successfully delivered outgoing messages
            var outgoingMessages = messages
                .Where(msg => msg.SenderId == data.CardNumber && !msg.DeliveryFailed)
                .OrderByDescending(msg => msg.Timestamp);

            foreach (var msg in outgoingMessages)
            {
                AddNanoChatEntry(count, msg, $"#{msg.SenderId:D4}", $"#{partnerId:D4}");
                count++;
            }
        }
    }

    private void AddNanoChatEntry(int count, NanoChatMessage msg, string sender, string recipient)
    {
        var messageText = Loc.GetString("log-probe-message-format",
            ("sender", sender),
            ("recipient", recipient),
            ("content", msg.Content));

        var entry = new NanoChatLogEntry(
            count,
            TimeSpan.FromSeconds(Math.Truncate(msg.Timestamp.TotalSeconds)).ToString(),
            messageText);

        ProbedDeviceContainer.AddChild(entry);
    }

    private void DisplayAccessLogs(List<PulledAccessLog> logs)
    {
        var count = 1;
        foreach (var log in logs)
        {
            AddAccessLog(log, count);
            count++;
        }
    }
    // Triad end

    private void AddAccessLog(PulledAccessLog log, int numberLabelText)
    {
        var timeLabelText = TimeSpan.FromSeconds(Math.Truncate(log.Time.TotalSeconds)).ToString();
        var accessorLabelText = log.Accessor;
        var entry = new LogProbeUiEntry(numberLabelText, timeLabelText, accessorLabelText);

        ProbedDeviceContainer.AddChild(entry);
    }
}
