- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: CargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: BoxCardboard
  alternateTitles:
  - CargoTechnicianCourier
  - CargoTechnicianPilot
  - CargoTechnicianClerk

- type: startingGear
  id: CargoTechGear
  equipment:
    id: CargoPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  #storage:
    #back:
    #- Stuff

- type: jobAlternateTitle
  id: CargoTechnicianCourier
  name: job-name-alt-cargotech-1

- type: jobAlternateTitle
  id: CargoTechnicianPilot
  name: job-name-alt-cargotech-2

- type: jobAlternateTitle
  id: CargoTechnicianClerk
  name: job-name-alt-cargotech-3
