# Renamed to Freelancer. Call new IDs Freelancer, not Contractor!
- type: job
  id: Contractor
  name: job-name-contractor
  description: job-description-contractor
  playTimeTracker: JobPassenger
  icon: "JobIconContractor"
  supervisors: job-supervisors-hire
  displayWeight: 40 # Top
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  alternateTitles:
  - FreelancerCitizen
  - FreelancerCivilian
  - FreelancerContractor
  - FreelancerPilot
  - FreelancerMercenary
  - FreelancerOffDutyEnforcer
  - FreelancerBountyHunter
  - FreelancerMiner
  - FreelancerSalvager
  - FreelancerSecurityGuard
  - FreelancerGunneryOperator
  - FreelancerConstructionWorker
  - FreelancerElectrician
  - FreelancerMechanic
  - FreelancerArchitect
  - FreelancerMaintenanceWorker
  - FreelancerAtmosphericEngineer
  - FreelancerElectricalEngineer
  - FreelancerMechanicalEngineer
  - FreelancerChemicalEngineer
  - FreelancerRoboticist
  - FreelancerFreelancer
  - FreelancerAssistant
  - FreelancerPsychologist
  - FreelancerPhysician
  - FreelancerTherapist
  - FreelancerPsychiatrist
  - FreelancerXenoarcheologist
  - FreelancerResearcher
  - FreelancerScientist
  - FreelancerPrivateInvestigator
  - FreelancerChaplain
  - FreelancerPriest
  - FreelancerJournalist
  - FreelancerMessTechnician
  - FreelancerCook
  - FreelancerBusinesswoman
  - FreelanceBusinessman
  - FreelanceBusinessperson
  - FreelanceEntrepreneur

# Considering Freelancer gives you much freedom, the titles are a multitude of roles:
- type: jobAlternateTitle
  id: FreelancerCitizen
  name: job-name-alt-freelancer-1

- type: jobAlternateTitle
  id: FreelancerCivilian
  name: job-name-alt-freelancer-2

- type: jobAlternateTitle
  id: FreelancerContractor
  name: job-name-alt-freelancer-3

- type: jobAlternateTitle
  id: FreelancerPilot
  name: job-name-alt-freelancer-4

- type: jobAlternateTitle
  id: FreelancerMercenary
  name: job-name-alt-freelancer-5

- type: jobAlternateTitle
  id: FreelancerOffDutyEnforcer
  name: job-name-alt-freelancer-6

- type: jobAlternateTitle
  id: FreelancerBountyHunter
  name: job-name-alt-freelancer-7

- type: jobAlternateTitle
  id: FreelancerMiner
  name: job-name-alt-freelancer-8

- type: jobAlternateTitle
  id: FreelancerSalvager
  name: job-name-alt-freelancer-9

- type: jobAlternateTitle
  id: FreelancerSecurityGuard
  name: job-name-alt-freelancer-10

- type: jobAlternateTitle
  id: FreelancerGunneryOperator
  name: job-name-alt-freelancer-11

- type: jobAlternateTitle
  id: FreelancerConstructionWorker
  name: job-name-alt-freelancer-12

- type: jobAlternateTitle
  id: FreelancerElectrician
  name: job-name-alt-freelancer-13

- type: jobAlternateTitle
  id: FreelancerMechanic
  name: job-name-alt-freelancer-14

- type: jobAlternateTitle
  id: FreelancerArchitect
  name: job-name-alt-freelancer-15

- type: jobAlternateTitle
  id: FreelancerMaintenanceWorker
  name: job-name-alt-freelancer-16

- type: jobAlternateTitle
  id: FreelancerAtmosphericEngineer
  name: job-name-alt-freelancer-17

- type: jobAlternateTitle
  id: FreelancerElectricalEngineer
  name: job-name-alt-freelancer-18

- type: jobAlternateTitle
  id: FreelancerMechanicalEngineer
  name: job-name-alt-freelancer-19

- type: jobAlternateTitle
  id: FreelancerChemicalEngineer
  name: job-name-alt-freelancer-20

- type: jobAlternateTitle
  id: FreelancerRoboticist
  name: job-name-alt-freelancer-21

- type: jobAlternateTitle
  id: FreelancerFreelancer
  name: job-name-alt-freelancer-22

- type: jobAlternateTitle
  id: FreelancerAssistant
  name: job-name-alt-freelancer-23

- type: jobAlternateTitle
  id: FreelancerPsychologist
  name: job-name-alt-freelancer-24

- type: jobAlternateTitle
  id: FreelancerPhysician
  name: job-name-alt-freelancer-25

- type: jobAlternateTitle
  id: FreelancerTherapist
  name: job-name-alt-freelancer-26

- type: jobAlternateTitle
  id: FreelancerPsychiatrist
  name: job-name-alt-freelancer-27

- type: jobAlternateTitle
  id: FreelancerXenoarcheologist
  name: job-name-alt-freelancer-28

- type: jobAlternateTitle
  id: FreelancerResearcher
  name: job-name-alt-freelancer-29

- type: jobAlternateTitle
  id: FreelancerScientist
  name: job-name-alt-freelancer-30

- type: jobAlternateTitle
  id: FreelancerPrivateInvestigator
  name: job-name-alt-freelancer-31

- type: jobAlternateTitle
  id: FreelancerChaplain
  name: job-name-alt-freelancer-32

- type: jobAlternateTitle
  id: FreelancerPriest
  name: job-name-alt-freelancer-33

- type: jobAlternateTitle
  id: FreelancerJournalist
  name: job-name-alt-freelancer-34

- type: jobAlternateTitle
  id: FreelancerMessTechnician
  name: job-name-alt-freelancer-35

- type: jobAlternateTitle
  id: FreelancerCook
  name: job-name-alt-freelancer-36

- type: jobAlternateTitle
  id: FreelancerBusinesswoman
  name: job-name-alt-freelancer-37

- type: jobAlternateTitle
  id: FreelanceBusinessman
  name: job-name-alt-freelancer-38

- type: jobAlternateTitle
  id: FreelanceBusinessperson
  name: job-name-alt-freelancer-39

- type: jobAlternateTitle
  id: FreelanceEntrepreneur
  name: job-name-alt-freelancer-40
