- type: loadoutGroup
  id: DoIJumpsuit
  name: loadout-group-contractor-jumpsuit
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ChiefEngineerJumpsuit
  - ChiefEngineerJumpskirt
  - ChiefEngineerTurtleneck
  - ChiefEngineerTurtleneckSkirt
  - ContractorClothingUniformJumpsuitSeniorEngineer
  - ContractorClothingUniformJumpskirtSeniorEngineer
  fallbacks:
  - ChiefEngineerJumpsuit

- type: loadoutGroup
  id: DoIHead
  name: loadout-group-contractor-head
  minLimit: 0
  loadouts:
  - ClothingHeadHatHardhatWhite
  subgroups:
  - InfrastructureHead
  - ContractorHead

- type: loadoutGroup
  id: DoINeck
  name: loadout-group-contractor-neck
  minLimit: 0
  loadouts:
  - ContractorClothingNeckCloakCe
  - ContractorClothingNeckMantleCE

- type: loadoutGroup
  id: DoIBackpack
  name: loadout-group-contractor-backpack
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ContractorClothingBackpackMessengerChiefEngineer
  subgroups:
  - InfrastructureBackpack
  fallbacks:
  - StationEngineerBackpack

- type: loadoutGroup
  id: DoIOuterClothing
  name: loadout-group-contractor-outerclothing
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ContractorClothingOuterWinterCE
  subgroups:
  - ContractorOuterClothing
