# New IDs should be SectorTechnician, not PlantTechnician.
- type: loadoutGroup
  id: PlantTechnicianHead
  name: loadout-group-contractor-head
  minLimit: 0
  loadouts:
  - StationEngineerHardhatYellow
  - StationEngineerHardhatOrange
  - StationEngineerHardhatRed
  - PlantHardhatBlue
  - PlantEngineeringBeret

- type: loadoutGroup
  id: PlantBelt
  name: loadout-group-contractor-belt
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ContractorClothingBeltUtility
  - ContractorClothingBeltUtilityFilled
  - ContractorClothingBeltStorageWaistbag
  - ContractorClothingBeltSalvageWebbingFilledNF
  - ContractorBoxFolderClipboard
  fallbacks:
  - ContractorClothingBeltUtilityFilled

- type: loadoutGroup
  id: PlantTechnicianJumpsuit
  name: loadout-group-contractor-jumpsuit
  minLimit: 1
  maxLimit: 1
  loadouts:
  - StationEngineerJumpsuit
  - StationEngineerJumpskirt
  - StationEngineerHazardsuit
  - AtmosphericTechnicianJumpsuit
  - AtmosphericTechnicianJumpskirt
  - AtmosphericTechnicianJumpsuitCasual
  fallbacks:
  - StationEngineerJumpsuit
