- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: ChefGear
  icon: "JobIconChef"
<<<<<<< HEAD
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:AddComponentSpecial
    components:
    - type: ProfessionalChef #Nyano - End Summary.
=======
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Kitchen
  extendedAccess:
  - Hydroponics
  - Bar
  alternateTitles:
  - ChefSousChef
  - ChefLineCook
  - ChefNutritionist
>>>>>>> 5149aaa14ff (Cosmetic Job Titles (#2407))

- type: startingGear
  id: ChefGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChefPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltChefFilled
  #storage:
    #back:
    #- Stuff

- type: jobAlternateTitle
  id: ChefSousChef
  name: job-name-alt-chef-1

- type: jobAlternateTitle
  id: ChefLineCook
  name: job-name-alt-chef-2

- type: jobAlternateTitle
  id: ChefNutritionist
  name: job-name-alt-chef-3
