- type: job
  id: Musician
  name: job-name-musician
  description: job-description-musician
  playTimeTracker: JobMusician
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: MusicianGear
  icon: "JobIconMusician"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MikuDay
    prototype: BoxPerformer
  alternateTitles:
  - MusicianRadioDJ
  - MusicianVisitingCelebrity
  - MusicianPerformer

- type: startingGear
  id: MusicianGear
  equipment:
    eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesBootsLaceup
    id: MusicianPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: jobAlternateTitle
  id: MusicianRadioDJ
  name: job-name-alt-musician-1

- type: jobAlternateTitle
  id: MusicianVisitingCelebrity
  name: job-name-alt-musician-2

- type: jobAlternateTitle
  id: MusicianPerformer
  name: job-name-alt-musician-3
