- type: department
  id: Security
  name: department-TriadDefenseForce
  description: department-TriadDefenseForce-description
  color: "#FFD580"
  weight: 120
  roles:
  - TDFChiefEnforcer
  - TDFWarden
  - TDFSectionLeader
  - TDFEnforcer
  - TDFMedic
  - TDFJuniorEnforcer
