using System.Text;
using Content.Shared._DV.Traits;
using Content.Shared._DV.Traits.Conditions;
using Content.Shared._Mono.Traits.Conditions; // Mono - Company condition
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._DV.Traits.UI;

[GenerateTypedNameReferences]
public sealed partial class TraitEntry : PanelContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public event Action<bool>? OnToggled;

    public bool IsSelected { get; private set; }
    public readonly int TraitCost;

    /// <summary>
    /// Whether the trait passes its conditions (species / job / mutex). False renders red and blocks selection.
    /// </summary>
    public bool MeetsConditions { get; private set; } = true;

    /// <summary>
    /// Triad: whether the player still has the budget (category/global trait slots and points) to add this trait.
    /// Pushed from the parent tab. An unselected, unaffordable entry renders grey and is unclickable; a selected
    /// one stays clickable so you can deselect to free budget. Does not gate already-selected entries.
    /// </summary>
    public bool Affordable { get; private set; } = true;

    private readonly TraitPrototype _trait;
    private bool _isUpdating;

    public TraitEntry(TraitPrototype trait)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _trait = trait;
        TraitCost = trait.Cost;

        // Tooltips are supplied on the panel; it needs to receive mouse-over to show them.
        MouseFilter = MouseFilterMode.Pass;

        TraitNameLabel.Text = Loc.GetString(trait.Name);
        TraitDescriptionLabel.SetMessage(Loc.GetString(trait.Description));

        // Format cost display: positive trait cost spends points, negative trait cost grants points.
        var costText = trait.Cost switch
        {
            > 0 => $"-{trait.Cost}",
            < 0 => $"+{System.Math.Abs(trait.Cost)}",
            _ => "0"
        };
        var costColor = trait.Cost > 0 ? "#6bff6b" : trait.Cost < 0 ? "#ff6b6b" : "#888888";
        TraitCostLabel.Text = costText;
        TraitCostLabel.ModulateSelfOverride = Color.FromHex(costColor);

        // Triad: the whole row is the hit target now (users kept missing the small checkbox). A transparent
        // full-bleed button (ClickArea) catches the click; the panel itself carries the green/red/grey stylebox.
        ClickArea.OnPressed += OnEntryPressed;

        // Build condition tooltips
        UpdateConditionTooltips();
        UpdateVisualState();

        // Triad: pin the description wrap width to the entry's real arranged width (see UpdateDescriptionWrap).
        OnResized += UpdateDescriptionWrap;
    }

    private void UpdateDescriptionWrap()
    {
        // This editor measures entries wider than they finally arrange (the lobby sprite panel claims space at
        // arrange time), so RichTextLabel caches a too-wide wrap and every line clips at the column edge. Pin the
        // label's max width to the entry's actual width, mirroring the manual width handling the global points bar
        // already uses in TraitsTab. Width - 54 = inner margins (10 + 10) + the description's 34px left indent.
        var available = Width - 54f;
        if (available > 0f && System.Math.Abs(TraitDescriptionLabel.MaxWidth - available) > 0.5f)
            TraitDescriptionLabel.MaxWidth = available;
    }

    private void UpdateConditionTooltips()
    {
        var conditionsTooltip = new StringBuilder();

        foreach (var condition in _trait.Conditions)
        {
            conditionsTooltip.Append(condition.GetTooltip(_prototype, _loc, 0));
        }

        if (conditionsTooltip.Length > 0)
        {
            var tooltip = Loc.GetString("trait-conditions-tooltip", ("conditions", conditionsTooltip.ToString())).ToString().Trim();
            var markupTooltip = CreateMarkupTooltip(tooltip);
            TooltipSupplier = _ => markupTooltip;
        }
        else
        {
            TooltipSupplier = null;
        }
    }

    /// <summary>
    /// Creates a tooltip control that properly parses markup.
    /// </summary>
    private static Tooltip CreateMarkupTooltip(string markupText)
    {
        var tooltip = new Tooltip();

        // Parse the markup into a FormattedMessage
        tooltip.SetMessage(FormattedMessage.FromMarkupOrThrow(markupText));

        return tooltip;
    }

    /// <summary>
    /// Updates whether conditions are met based on current job/species.
    /// </summary>
    public void UpdateConditionsMet(ProtoId<JobPrototype>? jobId, ProtoId<SpeciesPrototype>? speciesId, IReadOnlySet<ProtoId<AntagPrototype>>? antagPreferences, IReadOnlySet<ProtoId<TraitPrototype>>? traits, string? companyName) // Mono - Company condition
    {
        MeetsConditions = true;

        foreach (var condition in _trait.Conditions)
        {
            var result = condition switch
            {
                IsSpeciesCondition speciesCond => CheckSpeciesCondition(speciesCond, speciesId),
                HasJobCondition jobCond => CheckJobCondition(jobCond, jobId),
                InDepartmentCondition deptCond => CheckDepartmentCondition(deptCond, jobId),
                HasCompCondition compCond => !compCond.Invert, // can't check in lobby but screws with the inversion logic
                IsAntagEligibleCondition antagEligibleCond => CheckAntagEligibleCondition(antagEligibleCond, antagPreferences),
                HasTraitCondition hasTrait => CheckHasTraitCondition(hasTrait, traits),
                InCompanyCondition inCompanyCond => CheckInCompanyCondition(inCompanyCond, companyName), // Mono - Company condition
                AnyOfCondition anyOfCond => CheckAnyOfCondition(anyOfCond, jobId, speciesId, antagPreferences, traits, companyName),
                _ => true,
            };

            // Apply inversion
            result ^= condition.Invert;

            if (!result)
            {
                MeetsConditions = false;
            }
        }

        // Conditions no longer met: force-deselect (e.g. a mutex partner was just picked, or species changed).
        if (!MeetsConditions && IsSelected)
        {
            SetSelected(false);
            OnToggled?.Invoke(false);
        }

        UpdateVisualState();
    }

    /// <summary>
    /// Triad: set by the parent tab after recomputing budget. Drives the grey "can't afford" state.
    /// </summary>
    public void SetAffordable(bool affordable)
    {
        Affordable = affordable;
        UpdateVisualState();
    }

    private bool CheckSpeciesCondition(IsSpeciesCondition condition, ProtoId<SpeciesPrototype>? speciesId)
    {
        if (!_prototype.TryIndex(speciesId, out var species))
            return false;

        return species == condition.Species;
    }

    private bool CheckJobCondition(HasJobCondition condition, ProtoId<JobPrototype>? jobId)
    {
        if (!_prototype.TryIndex(jobId, out var job))
            return false;

        return job == condition.Job;
    }

    private bool CheckDepartmentCondition(InDepartmentCondition condition, ProtoId<JobPrototype>? jobId)
    {
        if (!_prototype.TryIndex(jobId, out var job))
            return false;

        if (!_prototype.TryIndex(condition.Department, out var department))
            return false;

        return department.Roles.Contains(job);
    }

    private bool CheckAntagEligibleCondition(IsAntagEligibleCondition condition, IReadOnlySet<ProtoId<AntagPrototype>>? antagPreferences)
    {
        if (antagPreferences is null)
            return false;

        return antagPreferences.Contains(condition.Antag);
    }

    private bool CheckHasTraitCondition(HasTraitCondition condition, IReadOnlySet<ProtoId<TraitPrototype>>? traits)
    {
        if (traits is null)
            return false;

        return traits.Contains(condition.Trait);
    }

    // Begin Mono - Company condition
    private bool CheckInCompanyCondition(InCompanyCondition condition, string? companyName) // Mono - Company condition
    {
        return string.Equals(condition.CompanyName, companyName);
    }
    // End Mono

    private bool CheckAnyOfCondition(AnyOfCondition condition, ProtoId<JobPrototype>? jobId, ProtoId<SpeciesPrototype>? speciesId, IReadOnlySet<ProtoId<AntagPrototype>>? antagPreferences, IReadOnlySet<ProtoId<TraitPrototype>>? traits, string? companyName) // Mono - Company condition
    {
        if (condition.Conditions.Count == 0)
            return false;

        // Return true if ANY child condition evaluates to true
        foreach (var childCondition in condition.Conditions)
        {
            var result = childCondition switch
            {
                IsSpeciesCondition speciesCond => CheckSpeciesCondition(speciesCond, speciesId),
                HasJobCondition jobCond => CheckJobCondition(jobCond, jobId),
                InDepartmentCondition deptCond => CheckDepartmentCondition(deptCond, jobId),
                HasCompCondition compCond => !compCond.Invert, // can't check in lobby
                IsAntagEligibleCondition antagEligibleCond => CheckAntagEligibleCondition(antagEligibleCond, antagPreferences),
                HasTraitCondition hasTrait => CheckHasTraitCondition(hasTrait, traits),
                InCompanyCondition inCompanyCond => CheckInCompanyCondition(inCompanyCond, companyName), // Mono - Company condition
                AnyOfCondition nestedAnyOf => CheckAnyOfCondition(nestedAnyOf, jobId, speciesId, antagPreferences, traits, companyName), // Recursive!
                _ => true,
            };

            // Apply child's inversion
            result ^= childCondition.Invert;

            // If any child passes, the AnyOf passes
            if (result)
                return true;
        }

        // None of the children passed
        return false;
    }

    private void OnEntryPressed(BaseButton.ButtonEventArgs args)
    {
        if (_isUpdating)
            return;

        // Rule-blocked entries (red) never toggle. Unaffordable unselected entries (grey) never toggle.
        // A selected entry always toggles off, so the player can free budget even when at the cap.
        if (!MeetsConditions)
            return;
        if (!IsSelected && !Affordable)
            return;

        SetSelected(!IsSelected);
        OnToggled?.Invoke(IsSelected);
    }

    public void SetSelected(bool selected)
    {
        _isUpdating = true;
        IsSelected = selected && MeetsConditions;
        UpdateVisualState();
        _isUpdating = false;
    }

    /// <summary>
    /// Triad: single source of truth for the entry's look. Four states, in priority order:
    /// rule-blocked (red, lock icon) &gt; selected (green) &gt; unaffordable (grey) &gt; available (normal).
    /// </summary>
    private void UpdateVisualState()
    {
        RemoveStyleClass("TraitsEntrySelected");
        RemoveStyleClass("TraitsEntryRuleBlocked");
        RemoveStyleClass("TraitsEntryDisabled");
        LockIcon.Visible = false;

        if (!MeetsConditions)
        {
            // Blocked by a rule the player could only change via species/job/other selections.
            // ClickArea disabled so the row gives no press feedback, not just a no-op click.
            LockIcon.Visible = true;
            AddStyleClass("TraitsEntryRuleBlocked");
            ClickArea.Disabled = true;
        }
        else if (IsSelected)
        {
            // Always clickable so it can be deselected, even when the category/points are at the cap.
            AddStyleClass("TraitsEntrySelected");
            ClickArea.Disabled = false;
        }
        else if (!Affordable)
        {
            // No budget left; greyed and unclickable until the player frees slots/points.
            AddStyleClass("TraitsEntryDisabled");
            ClickArea.Disabled = true;
        }
        else
        {
            ClickArea.Disabled = false;
        }

        UpdateConditionTooltips();
    }
}
